openapi: 3.1.0
info:
  title: Rekognition
  version: '1.0'
  summary: AWS Rekognition Image Processing APIs
  description: AWS Rekognition Image Processing APIs
  contact:
    name: Leor Brenman
    email: lbrenman99@hotmail.com
servers:
  - url: 'http://localhost:3000'
    description: Local Host
  - url: 'https://localhost:3000'
    description: Published
paths: {}
components:
  schemas: {}
  securitySchemes:
    apikey:
      name: apikey
      type: apiKey
      in: query
security:
  - apikey: []
