openapi: 3.1.0
info:
  title: Rekognition
  version: '1.0'
  summary: AWS Rekognition based API
  description: AWS Rekognition based API
  contact:
    name: Leor Brenman
    email: lbrenman99@hotmail.com
servers:
  - url: 'http://localhost:3000'
    description: Leor Brenman
paths:
  /detectLabels:
    post:
      summary: ''
      operationId: post-detectLabels
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../models/detectLabelResponse.yaml
      description: Detect objects in an image and return as labels
      security:
        - apikey: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../models/image.yaml
components:
  schemas: {}
  securitySchemes:
    apikey:
      name: apikey
      type: apiKey
      in: query
tags:
  - name: Rekognition
